services:
  rs-kerdev:
    image: rs-kerdev
    stdin_open: true
    tty: true
    volumes:
      - ~/Dev/rs-kerdev/src:/src
    devices:
      - /dev/kvm:/dev/kvm
    build:
      context: .
      dockerfile: Dockerfile
